### PR TITLE
Change the behavior of the stats

### PR DESCRIPTION
**Pull request by winkhanh**
Check the database config if needed

### CODE REVIEW

**Comment by MichaelGatesDev** [comment]
NA should be displayed as N/A for consistency

**Comment by MichaelGatesDev** [comment]
I will merge the PR as soon as I test that it works.. tomorrow.

**Comment by MichaelGatesDev** [comment]
There are now merge conflicts that must be resolved first.

**Comment by nthungdev** [comment]
@winkhanh are you still working on this? If not, we can close this PR.

**Comment by winkhanh** [comment]
Close PR

**Pull request closed without merging**
